### ISSUE TITLE
Forcing ZGC on potentially unsupported systems

### ISSUE THREAD

**Issue by yzaoui** [korlibs/korge-plugins#25]
Right now, `runJVM` runs ZGC if the Java version is 14+. Not all systems running 14+ support ZGC. For instance, I'm running Windows 8.1, [which meets the requirements of Java 14](https://www.oracle.com/java/technologies/javase/products-doc-jdk14certconfig.html), but when I run `runJVM` the task fails with `ZGC requires Windows version 1803 or later`.

I tried looking for a way to add a check for ZGC support in `Jvm.kt`, but no luck. Could grab the `os.name` and `os.version` from system properties, but maybe it's better to just modify the check to allow `JVM_USE_ZGC` to be explicitly `false`?

**Comment by soywiz** [comment]
Thanks for reporting!

We were not aware of the issue. Right now we are in the process of restructuring all the projects for the 2.0, and that includes rewriting this gradle plugin. We will have that into account.

Maybe we could change this:
```
val useZgc = (System.getenv("JVM_USE_ZGC") == "true") || (javaVersion.majorVersion.toIntOrNull() ?: 8) >= 14
```
into this (or a clearer variant with a when) so you can specify `JVM_USE_ZGC=false` and maybe supporting reading a property too, so you can configure it globally on the ~/.gradle/gradle.properties:
```
val useZgc = (System.getenv("JVM_USE_ZGC") == "true") || ((javaVersion.majorVersion.toIntOrNull() ?: 8) >= 14 && (System.getenv("JVM_USE_ZGC") != "false"))
```

Alternatively if you are aware of a simple and cheap way to detect the availability of ZGC (instead of just checking 14 or greater), let me know. That would be awesome since no configuration would be required

**Comment by yzaoui** [comment]
It doesn't seem like there's a way to check for ZGC sadly. Closest thing might be to check the `os.version` but that seems unreliable. The solution you wrote is personally what I would go for, with a mention of `JVM_USE_ZGC` in [the docs](https://korlibs.soywiz.com/korge/setup/).

**Comment by soywiz** [comment]
Okay. Makes sense.

**Comment by soywiz** [comment]
This was added to the 2.0 plugin already
